# var_name_to_feat

feat_order_summary_audio = ['F0 M', 'F0 CV', 'F0 P20', 'F0 P80', 'F0 SD rising slope', 'Jitter M',
                            'F1 frequency M', 'F1 frequency CV', 'F1 bandwidth M', 'F2 frequency M',
                            'F2 frequency CV', 'F2 bandwidth CV', 'F3 frequency CV', 'F3 bandwidth M',
                            'F3 bandwidth CV', 'Loudness CV', 'Loudness P20', 'Loudness P range',
                            'Loudness M rising slope', 'Loudness SD rising slope', 'Loudness M falling slope',
                            'Harmonics to noise ratio M', 'Shimmer M', 'Equivalent sound level M',
                            'Alpha ratio (voiced) M', 'Alpha ratio (unvoiced) M', 'Hammarberg index (voiced) M',
                            'Hammarberg index (voiced) CV', 'Hammarberg index (unvoiced) M', 'Spectral slope 0-500 (voiced) M',
                            'Spectral slope 500-1500 (voiced) M', 'Spectral slope 0-500 (unvoiced) M',
                            'Spectral slope 500-1500 (unvoiced) M', 'Spectral flux CV', 'Spectral flux (voiced) M',
                            'Spectral flux (voiced) CV', 'F1 amplitude M', 'F2 amplitude M', 'F3 amplitude M',
                            'MFCC1 M', 'MFCC1 (voiced) M', 'MFCC2 M', 'MFCC2 (voiced) M', 'MFCC3 (voiced) M',
                            'MFCC3 (voiced) CV', 'MFCC4 (voiced) M', 'Loudness peaks per second M',
                            'Voiced segments per second M', 'Voiced segment length M', 'Voiced segment length CV']
                            
feat_order_summary_video = ['AU04 (brow lowerer) M', 'AU04 (brow lowerer) P20', 'AU04 (brow lowerer) P50', 'AU04 (brow lowerer) P80',
                            'AU06 (cheek raiser) M', 'AU06 (cheek raiser) P20', 'AU06 (cheek raiser) P50', 'AU06 (cheek raiser) P80',
                            'AU07 (lid tightener) M', 'AU07 (lid tightener) CV', 'AU07 (lid tightener) P50', 'AU07 (lid tightener) P80',
                            'AU10 (upper lip raiser) M', 'AU10 (upper lip raiser) CV', 'AU10 (upper lip raiser) P20',
                            'AU10 (upper lip raiser) P50', 'AU10 (upper lip raiser) P80', 'AU10 (upper lip raiser) P range',
                            'AU12 (lip corner puller) M', 'AU12 (lip corner puller) P50', 'AU12 (lip corner puller) P80',
                            'AU14 (dimpler) M', 'AU14 (dimpler) P20', 'AU14 (dimpler) P50', 'AU14 (dimpler) P80',
                            'AU15 (lip corner depressor) N peaks', 'AU17 (chin raiser) M', 'AU17 (chin raiser) P80',
                            'AU17 (chin raiser) N peaks', 'AU20 (lip stretcher) P80', 'AU23 (lip tightener) M', 'AU26 (jaw drop) M',
                            'AU26 (jaw drop) P range', 'AU26 (jaw drop) N peaks'
                            ]
                            
feat_order_summary_multi = ['F0 M', 'F0 CV', 'F0 P20', 'F0 P50', 'F0 P80', 'F0 P range', 'F0 SD rising slope', 'F0 SD falling slope',
                            'Loudness CV', 'Loudness P20', 'Loudness P50', 'Loudness P range', 'Loudness M rising slope',
                            'Loudness SD rising slope', 'Loudness M falling slope', 'Loudness SD falling slope', 'Spectral flux CV',
                            'MFCC1 M', 'MFCC2 M', 'Jitter M', 'Jitter CV', 'Shimmer M', 'Shimmer CV', 'Harmonics to noise ratio M',
                            'F1 frequency M','F1 frequency CV','F1 bandwidth M','F1 amplitude M','F2 frequency M','F2 frequency CV',
                            'F2 bandwidth M','F2 bandwidth CV','F2 amplitude M','F3 frequency CV','F3 bandwidth M','F3 bandwidth CV',
                            'F3 amplitude M','F3 amplitude CV','Hammarberg index (voiced) M','Spectral slope 0-500 (voiced) M',
                            'Spectral slope 500-1500 (voiced) M','Spectral flux (voiced) M','Spectral flux (voiced) CV',
                            'MFCC1 (voiced) M','MFCC2 (voiced) M','MFCC3 (voiced) M','MFCC3 (voiced) CV','MFCC4 (voiced) M',
                            'Alpha ratio (unvoiced) M','Hammarberg index (unvoiced) M','Spectral slope 0-500 (unvoiced) M',
                            'Spectral flux (unvoiced) M','Loudness peaks per second M','Voiced segment length CV',
                            'Unvoiced segment length CV','Equivalent sound level M','AU04 (brow lowerer) M','AU04 (brow lowerer) CV',
                            'AU04 (brow lowerer) P20','AU04 (brow lowerer) P50','AU04 (brow lowerer) P80','AU04 (brow lowerer) P range',
                            'AU04 (brow lowerer) N peaks','AU05 (upper lid raiser) N peaks','AU06 (cheek raiser) M',
                            'AU06 (cheek raiser) P80','AU06 (cheek raiser) P range','AU06 (cheek raiser) N peaks',
                            'AU07 (lid tightener) M','AU07 (lid tightener) CV','AU07 (lid tightener) P80',
                            'AU07 (lid tightener) P range','AU07 (lid tightener) N peaks','AU10 (upper lip raiser) M',
                            'AU10 (upper lip raiser) CV','AU10 (upper lip raiser) P20','AU10 (upper lip raiser) P50',
                            'AU10 (upper lip raiser) P80','AU10 (upper lip raiser) P range','AU10 (upper lip raiser) N peaks',
                            'AU12 (lip corner puller) M','AU12 (lip corner puller) P20','AU12 (lip corner puller) P50',
                            'AU12 (lip corner puller) P80','AU12 (lip corner puller) P range','AU12 (lip corner puller) N peaks',
                            'AU14 (dimpler) P50','AU14 (dimpler) P range','AU15 (lip corner depressor) N peaks','AU17 (chin raiser) CV',
                            'AU17 (chin raiser) P80','AU17 (chin raiser) P range','AU17 (chin raiser) N peaks','AU23 (lip tightener) M',
                            'AU25 (lips part) N peaks','AU45 (blink) CV']

var_name_to_feat_m1 = {"hired_aid": "Hired aid for house chores",
                       "has_TV": "House has TV",
                        "has_paid_TV": "House has paid TV",
                        "has_radio": "House has radio",
                        "has_audio_system": "House has audio system",
                        "has_computer": "House has computer",
                        "has_cell_phone": "House has cellphone",
                        "has_internet": "House has internet",
                        "has_phone": "House has phone land line",
                        "has_iron": "House has clothes iron",
                        "has_blender": "House has blender",
                        "has_refrigerator": "House has refrigerator",
                        "has_gas_stove": "House has gas stove",
                        "has_other_stove": "House has other stove",
                        "has_wash_dry": "House has washing or drying machine",
                        "has_microwave": "House has microwave",
                        "cooking_room_kitchen": "Room used to cook: kitchen",
                        "cook_sleep":"Is the room used to cook used to sleep too",
                        "food_expense": "Is the food expense the same for all the household",
                        "result_elcsa_Food safety": "ELCSA result: Food security",
                        "result_elcsa_Mild insecurity": "ELCSA result: Mild insecurity",
                        "result_elcsa_Moderate insecurity": "ELCSA result: Moderate insecurity",
                        "result_elcsa_Severe insecurity": "ELCSA result: Severe insecurity"}

feat_order_summary_m1 = ["hired_aid","has_TV","has_paid_TV","has_radio","has_audio_system","has_computer","has_cell_phone",
                        "has_internet","has_phone","has_iron","has_blender","has_refrigerator","has_gas_stove","has_other_stove",
                        "has_wash_dry","has_microwave","cooking_room_kitchen","cook_sleep","food_expense",
                        "result_elcsa_Food safety","result_elcsa_Mild insecurity","result_elcsa_Moderate insecurity",
                        "result_elcsa_Severe insecurity"]

var_name_to_feat_m2 = {"exp_fruits":"Expense in fruits",
                       "exp_vegetables":"Expense in vegetables",
                       "exp_corn": "Expense in corn",
                       "exp_bread":"Expense in bread",
                       "exp_grains":"Expense in grains",
                       "exp_oil_sugar":"Expense in oil and sugar",
                       "exp_meat":"Expense in dairy",
                       "exp_dairy":"Expense in eggs",
                       "exp_eggs":"Expense in snacks",
                       "exp_snacks":"Expense in snacks",
                       "exp_fast_food":"Expense in fast food",
                       "exp_bottled_water":"Expense in bottled water",
                       "exp_soda":"Expense in soda",
                       "exp_alcohol":"Expense in alcohol",
                       "exp_tobacco":"Expense in tobacco",
                       "exp_not_homemade":"Expense in takeout or restaurant meals",
                       "total_food_expense":"Total expense in food",
                       "total_health_expense":"Total expense in healthcare"
                       }

feat_order_summary_m2 = ["exp_fruits", "exp_vegetables", "exp_corn", "exp_bread", "exp_grains", "exp_oil_sugar",
                         "exp_meat", "exp_dairy", "exp_eggs", "exp_snacks", "exp_fast_food", "exp_bottled_water", 
                         "exp_soda", "exp_alcohol", "exp_tobacco", "exp_not_homemade", "total_food_expense", 
                         "total_health_expense"]


var_name_to_feat_m3 = {"ob_diag":"Obesity diagnosis",
                    "dm_diag":"Diabetes Mellitus diagnosis",
                    "hbp_diag":"High Blood Pressure diagnosis",
                    "cvd_ha_hi":"Heart Attack or Heart Infarction diagnosis",
                    "cvd_chest_angina": "Chest Angina diagnosis",
                    "cvd_heart_failure":"Heart Failure diagnosis",
                    "kd_diag_uti":"Urinary Track Infection diagnosis",
                    "kd_diag_k_stones":"Kidney stones diagnosis",
                    "kd_diag_renal_fail":"Renal Failure diagnosis",
                    "chol_diag":"High cholesterol diagnosis",
                    "trig_diag":"High Triglycerides diagnosis",
                    "fmh_father_dm":"Father with Diabetes Mellitus",
                    "fmh_father_hbp":"Father with High Blood Pressure",
                    "fmh_father_hi":"Father with Heart Infarction",
                    "fmh_father_chol_tri":"Father with High Cholesterol or Triglycerides",
                    "fmh_mother_dm":"Mother with Diabetes Mellitus",
                    "fmh_mother_hbp":"Mother with High Blood Pressure",
                    "fmh_mother_hi":"Mother with Heart Infarction",
                    "fmh_mother_chol_tri":"Mother with High Cholesterol or Triglycerides",
                    "fmh_sibling_dm":"Sibling with Diabetes Mellitus",
                    "fmh_sibling_hbp":"Sibling with High Blood Pressure",
                    "fmh_sibling_hi":"Sibling with Heart Infarction",
                    "fmh_sibling_chol_tri":"Sibling with High Cholesterol or Triglycerides",
                    "violence":"Experienced Violence",
                    "present_smoker":"Smokes in the present",
                    "past_smoker":"Smoked in the past",
                    "sight_aid":"Needs sight aid",
                    "hearing_aid":"Needs hearing aid",
                    "walk_difficulty":"Has difficulty walking",
                    "memory_difficulty":"Has difficulty with memory",
                    "self_care_difficulty":"Has difficulty with self-care",
                    "communication_difficulty":"Has difficulty with communication",
                    "sex_random_adult":"Sex",
                    "hc_inst_IMSS":"Seeks healthcare at: IMSS",
                    "hc_inst_ISSSTE":"Seeks healthcare at: ISSSTE",
                    "hc_inst_ISSSTE_st":"Seeks healthcare at: State ISSSTE",
                    "hc_inst_PEMEX":"Seeks healthcare at: PEMEX",
                    "hc_inst_Defensa":"Seeks healthcare at: Defensa",
                    "hc_inst_Marina":"Seeks healthcare at: Marina",
                    "hc_inst_SSA":"Seeks healthcare at: SSA",
                    "hc_inst_IMSS_Pro":"Seeks healthcare at: IMSS Prospera",
                    "hc_inst_pharma":"Seeks healthcare at: Pharmacy",
                    "hc_inst_private":"Seeks healthcare at: Private care",
                    "hc_inst_selfmed":"Seeks healthcare at: Self-Medication",
                    "hc_inst_other":"Seeks healthcare at: Other",
                    "hc_inst_doesnotgo":"Seeks healthcare at: Does not go",
                    "hc_inst_doesnotknow":"Seeks healthcare at: Does not know",
                    "speak_ind_lang":"Speaks indigenous language",
                    "attend_school":"Attends school",
                    "grade_achieved":"Grade achieved",
                    "marital_status":"Marital status",
                    "worked_hours": "Worked hours last week",
                    "diff_use_legs":"Difficulty using legs",
                    "diff_see":"Difficulty seeing",
                    "diff_use_arms":"Difficulty using arms",
                    "diff_learn":"Difficulty learning",
                    "diff_hear":"Difficulty hearing",
                    "diff_self_care":"Difficulty with self-care",
                    "diff_speak":"Difficulty speaking",
                    "diff_daily_act":"Difficulty with daily activity",
                    "fruit_intake":"Fruit intake >= 7 days",
                    "vegetable_intake":"Vegetable intake >= 7 days",
                    "legumes_intake":"Legumes intake >= 3 days",
                    "meat_intake":"Meat intake >= 3 days",
                    "proc_meat_intake":"Procesed meat intake >= 3 days",
                    "fast_food_intake":"Fast food intake >= 3 days",
                    "sweets_intake":"Sweets intake >= 3 days",
                    "sug_cereal_intake":"Sweetened Cereals intake >= 3 days",
                    "nd_sug_bev_intake":"Non-Dairy Sugary Beverages intake >= 3 days",
                    "water_intake":"Water intake >= 7 days",
                    "dairy_sug_bev_intake":"Dairy Sugary Beverages intake >= 3 days",
                    "dairy_intake":"Dairy intake >= 3 days",
                    "egg_intake":"Eggs intake >= 3 days",
                    "kinship_health_info_adult_Great grandparent": "Kinship: Great-grandparent",
                    "kinship_health_info_adult_Grandparent": "Kinship: Grandparent",
                    "kinship_health_info_adult_Mother/father or uncle/aunt": "Kinship: Father or Uncle/Aunt",
                    "kinship_health_info_adult_Mother/father-in-law": "Kinship: Mother/father-in-law",
                    "kinship_health_info_adult_No kinship":"Kinship: No kinship",
                    "kinship_health_info_adult_Parent":"Kinship: Parent",
                    "kinship_health_info_adult_Parent or uncle/aunt": "Kinship: Parent or uncle/aunt",
                    "kinship_health_info_adult_Partner": "Kinship: Partner",
                    "kinship_health_info_adult_Partner or brother/sister-in-law":"Kinship: Partner or brother/sister-in-law",
                    "kinship_health_info_adult_Sibling":"Kinship: Sibling",
                    "kinship_health_info_adult_Sibling or cousin":"Kinship: Sibling or cousin",
                    "kinship_health_info_adult_Unknown":"Kinship: Unknown",
                    "marital_status_divorced":"Marital status: divorced",
                    "marital_status_free_union":"Marital status: free union",
                    "marital_status_married":"Marital status: married",
                    "marital_status_separated_free_union":"Marital status: separated free union",
                    "marital_status_separated_marriage":"Marital status: separated marriage",
                    "marital_status_single":"Marital status: single",
                    "marital_status_widowed":"Marital status: widowed",
                    "grade_achieved_bachellors":"Grade achieved: bachellors",
                    "grade_achieved_doctorate":"Grade achieved: doctorate",
                    "grade_achieved_masters":"Grade achieved: masters",
                    "grade_achieved_none":"Grade achieved: none",
                    "grade_achieved_normal_basica":"Grade achieved: normal basica",
                    "grade_achieved_normal_licenciatura":"Grade achieved: licenciatura",
                    "grade_achieved_pre-school":"Grade achieved: pre-school",
                    "grade_achieved_preparatoria":"Grade achieved: preparatoria",
                    "grade_achieved_primaria":"Grade achieved: primaria",
                    "grade_achieved_secundaria":"Grade achieved: secundaria",
                    "grade_achieved_tec_com_studies_preparatoria":"Grade achieved: preparatoria with technical studies",
                    "grade_achieved_tec_com_studies_primaria":"Grade achieved: primaria with technical studies",
                    "grade_achieved_tec_com_studies_secundaria":"Grade achieved: secundaria with technical studies",
                    "region_Centre":"Region: Centre",
                    "region_Mexico City":"Region: Mexico City",
                    "region_North":"Region: North",
                    "region_South":"Region: South",
                    "strata_1st_strata":"Sociodemographic strata: 1st strata",
                    "strata_2nd_strata":"Sociodemographic strata: 2nd strata",
                    "strata_3rd_strata":"Sociodemographic strata: 3rd strata",
                    "strata_4th_strata":"Sociodemographic strata: 4th strata",
                    "age_health_info_adult_20-29":"Age: 20-29 years",
                    "age_health_info_adult_30-39":"Age: 30-39 years",
                    "age_health_info_adult_40-49":"Age: 40-49 years",
                    "age_health_info_adult_50-59":"Age: 50-59 years",
                    "age_health_info_adult_60-69":"Age: 60-69 years",
                    "age_health_info_adult_70-79":"Age: 70-79 years",
                    "age_health_info_adult_80-89":"Age: 80-89 years",
                    "sex_random_adult_female":"Sex: female",
                    "sex_random_adult_male":"Sex: male"}

feat_order_summary_m3 = ["ob_diag", "dm_diag","hbp_diag","cvd_ha_hi","cvd_chest_angina", 
                        "cvd_heart_failure","kd_diag_uti","kd_diag_k_stones", 
                        "kd_diag_renal_fail","chol_diag","trig_diag","fmh_father_dm",
                        "fmh_father_hbp","fmh_father_hi","fmh_father_chol_tri","fmh_mother_dm",
                        "fmh_mother_hbp","fmh_mother_hi","fmh_mother_chol_tri","fmh_sibling_dm",
                        "fmh_sibling_hbp","fmh_sibling_hi","fmh_sibling_chol_tri","violence",
                        "present_smoker","past_smoker","sight_aid","hearing_aid","walk_difficulty",
                        "memory_difficulty","self_care_difficulty","communication_difficulty",
                        "sex_random_adult","hc_inst_IMSS","hc_inst_ISSSTE","hc_inst_ISSSTE_st",
                        "hc_inst_PEMEX","hc_inst_Defensa","hc_inst_Marina","hc_inst_SSA","hc_inst_IMSS_Pro",
                        "hc_inst_pharma","hc_inst_private","hc_inst_selfmed","hc_inst_other",
                        "hc_inst_doesnotgo","hc_inst_doesnotknow","speak_ind_lang","attend_school",
                        "grade_achieved","marital_status","worked_hours","diff_use_legs","diff_see",
                        "diff_use_arms","diff_learn","diff_hear","diff_self_care","diff_speak",
                        "diff_daily_act","fruit_intake","vegetable_intake","legumes_intake",
                        "meat_intake","proc_meat_intake","fast_food_intake","sweets_intake",
                        "sug_cereal_intake","nd_sug_bev_intake","water_intake","dairy_sug_bev_intake",
                        "dairy_intake","egg_intake","kinship_health_info_adult_Grandparent",
                        "kinship_health_info_adult_Great grandparent","kinship_health_info_adult_Mother/father or uncle/aunt",
                        "kinship_health_info_adult_Mother/father-in-law","kinship_health_info_adult_No kinship",
                        "kinship_health_info_adult_Parent","kinship_health_info_adult_Parent or uncle/aunt",
                        "kinship_health_info_adult_Partner","kinship_health_info_adult_Partner or brother/sister-in-law",
                        "kinship_health_info_adult_Sibling","kinship_health_info_adult_Sibling or cousin",
                        "kinship_health_info_adult_Unknown","marital_status_divorced","marital_status_free_union",
                        "marital_status_married","marital_status_separated_free_union","marital_status_separated_marriage",
                        "marital_status_single","marital_status_widowed","grade_achieved_bachellors","grade_achieved_doctorate",
                        "grade_achieved_master","grade_achieved_none","grade_achieved_normal_basica","grade_achieved_normal_licenciatura",
                        "grade_achieved_pre-school","grade_achieved_preparatoria","grade_achieved_primaria","grade_achieved_secundaria",
                        "grade_achieved_tec_com_studies_preparatoria","grade_achieved_tec_com_studies_primaria",
                        "grade_achieved_tec_com_studies_secundaria","region_Centre","region_Mexico City","region_North","region_South",
                        "strata_1st_strata","strata_2nd_strata","strata_3rd_strata","strata_4th_strata","age_health_info_adult_20-29",
                        "age_health_info_adult_30-39","age_health_info_adult_40-49","age_health_info_adult_50-59","age_health_info_adult_60-69",
                        "age_health_info_adult_70-79","age_health_info_adult_80-89","sex_random_adult_female","sex_random_adult_male"]

var_name_to_feat_m4 = {"glucose_value":"Blood glucose",
                       "hba1c_value":"Glucosilated hemoglobin",
                       "albumin_value":"Albumin",
                       "hdl_chol_value":"HDL Cholesterol",
                       "ldl_chol_value":"LDL Cholesterol",
                       "creatinine_value":"Creatinine",
                       "insulin_value":"Insulin",
                       "trig_value":"Triglycerides",
                       "days_intense_phy_act":"Days per week of intense physical activity",
                       "days_moderate_phy_act":"Days per week of moderate physical activity",
                       "days_walking":"Days waliking",
                       "hemoglobin_value":"Hemoglobin",
                       "minutes_sitting":"Minutes sitting down during the day",
                       "BMI_random_adult":"Body Mass Index",
                       "av_waist":"Waist circumference",
                       "av_systolic_bp":"Systolic Blood Pressure",
                       "av_dyastolic_bp":"Diastolic Blood Pressure"}

feat_order_summary_m4 = ["glucose_value","hba1c_value","albumin_value","hdl_chol_value","ldl_chol_value",
                         "creatinine_value","insulin_value","trig_value","days_intense_phy_act",
                         "days_moderate_phy_act","days_walking","hemoglobin_value","minutes_sitting",
                         "BMI_random_adult","av_waist","av_systolic_bp","av_dyastolic_bp"]

var_name_to_feat_m5 = {"nut_cont_knowledge":"Knows packaging contains Nutritional Information",
                       "nut_inf_decision":"Uses Nutritional Information to make buying decision",
                       "use_dng":"Uses Nutritional Information: Daily Nutritional Guide",
                       "use_nut_seal":"Uses packaging info: Nutritional Seals",
                       "use_legends":"Uses packaging info: explicit nutritional legends",
                       "use_nut_inf":"Uses packaging info: Nutritional Information",
                       "use_ing_list":"Uses packaging info: ingredient list",
                       "use_none":"Uses packaging info: none",
                       "use_not_know":"Uses packaging info: does not know",
                       "unhealthy_product":"Identifies unhealthy product",
                       "sodium_level":"Identifies correct sodium level",
                       "calories":"Identifies correct number of calories",
                       "region_1":"Region: North",
                       "region_2":"Region: Centre",
                       "region_3":"Region: Mexico City",
                       "region_4":"Region: South",
                       "strata_1st_strata":"Sociodemographic strata: 1st strata",
                       "strata_2nd_strata":"Sociodemographic strata: 2nd strata",
                       "strata_3rd_strata":"Sociodemographic strata: 3rd strata",
                       "strata_4th_strata":"Sociodemographic strata: 4th strata",
                       "age_nut_know_adult_20-29":"Age: 20-29 years",
                       "age_nut_know_adult_30-39":"Age: 30-39 years",
                       "age_nut_know_adult_40-49":"Age: 40-49 years",
                       "age_nut_know_adult_50-59":"Age: 50-59 years",
                       "age_nut_know_adult_60-69":"Age: 60-69 years",
                       "age_nut_know_adult_70-79":"Age: 70-79 years",
                       "age_nut_know_adult_80-89":"Age: 80-89 years",
                       "sex_nut_know_adult_female":"Sex: female",
                       "sex_nut_know_adult_male":"Sex: male",
                       "buy_choice_almost always":"Buy choice based on packaging info: almost always",
                       "buy_choice_almost never":"Buy choice based on packaging info: almost never",
                       "buy_choice_always":"Buy choice based on packaging info: always",
                       "buy_choice_never":"Buy choice based on packaging info: never",
                       "buy_choice_sometimes":"Buy choice based on packaging info: sometimes",
                       "time_choice_Does not see it":"Time looking at packaging info: does not see it",
                       "time_choice_From 30 to 60 seconds":"Time looking at packaging info: 30 to 60 seconds",
                       "time_choice_Less than 30 seconds":"Time looking at packaging info: < 30 seconds",
                       "time_choice_More than a minute":"Time looking at packaging info: > 1 minute",
                       "energy_importance_Important":"Importance of Energy content info: important",
                       "energy_importance_Least important":"Importance of Energy content info: least important",
                       "energy_importance_Most important":"Importance of Energy content info: most important",
                       "energy_importance_Neutral":"Importance of Energy content info: neutral",
                       "energy_importance_Unimportant":"Importance of Energy content info: unimportant",
                       "sodium_importance_Important":"Importance of Sodium content info: important",
                       "sodium_importance_Least important":"Importance of Sodium content info: least important",
                       "sodium_importance_Most important":"Importance of Sodium content info: most important",
                       "sodium_importance_Neutral":"Importance of Sodium content info: neutral",
                       "sodium_importance_Unimportant":"Importance of Sodium content info: unimportant",
                       "sugars_importance_Important":"Importance of Sugars content info: important",
                       "sugars_importance_Least important":"Importance of Sugars content info: least important",
                       "sugars_importance_Most important":"Importance of Sugars content info: most important",
                       "sugars_importance_Neutral":"Importance of Sugars content info: neutral",
                       "sugars_importance_Unimportant":"Importance of Sugars content info: unimportant",
                       "fats_importance_Important":"Importance of Fats content info: important",
                       "fats_importance_Least important":"Importance of Fats content info: least important",
                       "fats_importance_Most important":"Importance of Fats content info: most important",
                       "fats_importance_Neutral":"Importance of Fats content info: neutral",
                       "fats_importance_Unimportant":"Importance of Fats content info: unimportant",
                       "sat_fats_importance_Important":"Importance of Saturated Fats content info: important",
                       "sat_fats_importance_Least important":"Importance of Saturated Fats content info: least important",
                       "sat_fats_importance_Most important":"Importance of Saturated Fats content info: most important",
                       "sat_fats_importance_Neutral":"Importance of Saturated Fats content info: neutral",
                       "sat_fats_importance_Unimportant":"Importance of Saturated Fats content info: unimportant",
                       "kinship_nut_know_adult_Grandparent":"Kinship: grandparent",
                       "kinship_nut_know_adult_Great grandparent":"Kinship: great-grandparent",
                       "kinship_nut_know_adult_Mother/father or uncle/aunt":"Kinship: father or Uncle/Aunt",
                       "kinship_nut_know_adult_Mother/father-in-law":"Kinship: mother/father-in-law",
                       "kinship_nut_know_adult_No kinship":"Kinship: no kinship",
                       "kinship_nut_know_adult_Parent":"Kinship: parent",
                       "kinship_nut_know_adult_Parent or uncle/aunt":"Kinship: parent or uncle/aunt",
                       "kinship_nut_know_adult_Partner":"Kinship: partner",
                       "kinship_nut_know_adult_Partner or brother/sister-in-law":"Kinship: partner or brother/sister-in-law",
                       "kinship_nut_know_adult_Sibling":"Kinship: sibling",
                       "kinship_nut_know_adult_Sibling or brother/sister-in-law":"Kinship: sibling or brother/sister-in-law",
                       "kinship_nut_know_adult_Sibling or cousin":"Kinship: sibling or cousin",
                       "kinship_nut_know_adult_Unknown":"Kinship: unknown"}

feat_order_summary_m5 = ["nut_cont_knowledge","nut_inf_decision","use_dng","use_nut_seal","use_legends",
                        "use_nut_inf","use_ing_list","use_none","use_not_know","unhealthy_product",
                        "sodium_level","calories","region_1","region_2","region_3","region_4","strata_1st_strata",
                        "strata_2nd_strata","strata_3rd_strata","strata_4th_strata","age_nut_know_adult_20-29",
                        "age_nut_know_adult_30-39","age_nut_know_adult_40-49","age_nut_know_adult_50-59",
                        "age_nut_know_adult_60-69","age_nut_know_adult_70-79","age_nut_know_adult_80-89",
                        "sex_nut_know_adult_female","sex_nut_know_adult_male","buy_choice_almost always",
                        "buy_choice_almost never","buy_choice_always","buy_choice_never","buy_choice_sometimes",
                        "time_choice_Does not see it","time_choice_From 30 to 60 seconds","time_choice_Less than 30 seconds",
                        "time_choice_More than a minute","energy_importance_Important","energy_importance_Least important",
                        "energy_importance_Most important","energy_importance_Neutral","energy_importance_Unimportant",
                        "sodium_importance_Important","sodium_importance_Least important","sodium_importance_Most important",
                        "sodium_importance_Neutral","sodium_importance_Unimportant","sugars_importance_Important",
                        "sugars_importance_Least important","sugars_importance_Most important","sugars_importance_Neutral",
                        "sugars_importance_Unimportant","fats_importance_Important","fats_importance_Least important",
                        "fats_importance_Most important","fats_importance_Neutral","fats_importance_Unimportant","sat_fats_importance_Important",
                        "sat_fats_importance_Least important"]

var_name_to_feat_unimodal = {"hired_aid": "Hired aid for house chores",
                       "has_TV": "House has TV",
                        "has_paid_TV": "House has paid TV",
                        "has_radio": "House has radio",
                        "has_audio_system": "House has audio system",
                        "has_computer": "House has computer",
                        "has_cell_phone": "House has cellphone",
                        "has_internet": "House has internet",
                        "has_phone": "House has phone land line",
                        "has_iron": "House has clothes iron",
                        "has_blender": "House has blender",
                        "has_refrigerator": "House has refrigerator",
                        "has_gas_stove": "House has gas stove",
                        "has_other_stove": "House has other stove",
                        "has_wash_dry": "House has washing or drying machine",
                        "has_microwave": "House has microwave",
                        "cooking_room_kitchen": "Room used to cook: kitchen",
                        "cook_sleep":"Is the room used to cook used to sleep too",
                        "food_expense": "Is the food expense the same for all the household",
                        "result_elcsa_Food safety": "ELCSA result: Food security",
                        "result_elcsa_Mild insecurity": "ELCSA result: Mild insecurity",
                        "result_elcsa_Moderate insecurity": "ELCSA result: Moderate insecurity",
                        "result_elcsa_Severe insecurity": "ELCSA result: Severe insecurity",
                        "exp_fruits":"Expense in fruits",
                       "exp_vegetables":"Expense in vegetables",
                       "exp_corn": "Expense in corn",
                       "exp_bread":"Expense in bread",
                       "exp_grains":"Expense in grains",
                       "exp_oil_sugar":"Expense in oil and sugar",
                       "exp_meat":"Expense in dairy",
                       "exp_dairy":"Expense in eggs",
                       "exp_eggs":"Expense in snacks",
                       "exp_snacks":"Expense in snacks",
                       "exp_fast_food":"Expense in fast food",
                       "exp_bottled_water":"Expense in bottled water",
                       "exp_soda":"Expense in soda",
                       "exp_alcohol":"Expense in alcohol",
                       "exp_tobacco":"Expense in tobacco",
                       "exp_not_homemade":"Expense in takeout or restaurant meals",
                       "total_food_expense":"Total expense in food",
                       "total_health_expense":"Total expense in healthcare",
                       "ob_diag":"Obesity diagnosis",
                    "dm_diag":"Diabetes Mellitus diagnosis",
                    "hbp_diag":"High Blood Pressure diagnosis",
                    "cvd_ha_hi":"Heart Attack or Heart Infarction diagnosis",
                    "cvd_chest_angina": "Chest Angina diagnosis",
                    "cvd_heart_failure":"Heart Failure diagnosis",
                    "kd_diag_uti":"Urinary Track Infection diagnosis",
                    "kd_diag_k_stones":"Kidney stones diagnosis",
                    "kd_diag_renal_fail":"Renal Failure diagnosis",
                    "chol_diag":"High cholesterol diagnosis",
                    "trig_diag":"High Triglycerides diagnosis",
                    "fmh_father_dm":"Father with Diabetes Mellitus",
                    "fmh_father_hbp":"Father with High Blood Pressure",
                    "fmh_father_hi":"Father with Heart Infarction",
                    "fmh_father_chol_tri":"Father with High Cholesterol or Triglycerides",
                    "fmh_mother_dm":"Mother with Diabetes Mellitus",
                    "fmh_mother_hbp":"Mother with High Blood Pressure",
                    "fmh_mother_hi":"Mother with Heart Infarction",
                    "fmh_mother_chol_tri":"Mother with High Cholesterol or Triglycerides",
                    "fmh_sibling_dm":"Sibling with Diabetes Mellitus",
                    "fmh_sibling_hbp":"Sibling with High Blood Pressure",
                    "fmh_sibling_hi":"Sibling with Heart Infarction",
                    "fmh_sibling_chol_tri":"Sibling with High Cholesterol or Triglycerides",
                    "violence":"Experienced Violence",
                    "present_smoker":"Smokes in the present",
                    "past_smoker":"Smoked in the past",
                    "sight_aid":"Needs sight aid",
                    "hearing_aid":"Needs hearing aid",
                    "walk_difficulty":"Has difficulty walking",
                    "memory_difficulty":"Has difficulty with memory",
                    "self_care_difficulty":"Has difficulty with self-care",
                    "communication_difficulty":"Has difficulty with communication",
                    "sex_random_adult":"Sex",
                    "hc_inst_IMSS":"Seeks healthcare at: IMSS",
                    "hc_inst_ISSSTE":"Seeks healthcare at: ISSSTE",
                    "hc_inst_ISSSTE_st":"Seeks healthcare at: State ISSSTE",
                    "hc_inst_PEMEX":"Seeks healthcare at: PEMEX",
                    "hc_inst_Defensa":"Seeks healthcare at: Defensa",
                    "hc_inst_Marina":"Seeks healthcare at: Marina",
                    "hc_inst_SSA":"Seeks healthcare at: SSA",
                    "hc_inst_IMSS_Pro":"Seeks healthcare at: IMSS Prospera",
                    "hc_inst_pharma":"Seeks healthcare at: Pharmacy",
                    "hc_inst_private":"Seeks healthcare at: Private care",
                    "hc_inst_selfmed":"Seeks healthcare at: Self-Medication",
                    "hc_inst_other":"Seeks healthcare at: Other",
                    "hc_inst_doesnotgo":"Seeks healthcare at: Does not go",
                    "hc_inst_doesnotknow":"Seeks healthcare at: Does not know",
                    "speak_ind_lang":"Speaks indigenous language",
                    "attend_school":"Attends school",
                    "grade_achieved":"Grade achieved",
                    "marital_status":"Marital status",
                    "worked_hours": "Worked hours last week",
                    "diff_use_legs":"Difficulty using legs",
                    "diff_see":"Difficulty seeing",
                    "diff_use_arms":"Difficulty using arms",
                    "diff_learn":"Difficulty learning",
                    "diff_hear":"Difficulty hearing",
                    "diff_self_care":"Difficulty with self-care",
                    "diff_speak":"Difficulty speaking",
                    "diff_daily_act":"Difficulty with daily activity",
                    "fruit_intake":"Fruit intake >= 7 days",
                    "vegetable_intake":"Vegetable intake >= 7 days",
                    "legumes_intake":"Legumes intake >= 3 days",
                    "meat_intake":"Meat intake >= 3 days",
                    "proc_meat_intake":"Procesed meat intake >= 3 days",
                    "fast_food_intake":"Fast food intake >= 3 days",
                    "sweets_intake":"Sweets intake >= 3 days",
                    "sug_cereal_intake":"Sweetened Cereals intake >= 3 days",
                    "nd_sug_bev_intake":"Non-Dairy Sugary Beverages intake >= 3 days",
                    "water_intake":"Water intake >= 7 days",
                    "dairy_sug_bev_intake":"Dairy Sugary Beverages intake >= 3 days",
                    "dairy_intake":"Dairy intake >= 3 days",
                    "egg_intake":"Eggs intake >= 3 days",
                    "kinship_health_info_adult_Great grandparent": "Kinship: Great-grandparent",
                    "kinship_health_info_adult_Grandparent": "Kinship: Grandparent",
                    "kinship_health_info_adult_Mother/father or uncle/aunt": "Kinship: Father or Uncle/Aunt",
                    "kinship_health_info_adult_Mother/father-in-law": "Kinship: Mother/father-in-law",
                    "kinship_health_info_adult_No kinship":"Kinship: No kinship",
                    "kinship_health_info_adult_Parent":"Kinship: Parent",
                    "kinship_health_info_adult_Parent or uncle/aunt": "Kinship: Parent or uncle/aunt",
                    "kinship_health_info_adult_Partner": "Kinship: Partner",
                    "kinship_health_info_adult_Partner or brother/sister-in-law":"Kinship: Partner or brother/sister-in-law",
                    "kinship_health_info_adult_Sibling":"Kinship: Sibling",
                    "kinship_health_info_adult_Sibling or cousin":"Kinship: Sibling or cousin",
                    "kinship_health_info_adult_Unknown":"Kinship: Unknown",
                    "marital_status_divorced":"Marital status: divorced",
                    "marital_status_free_union":"Marital status: free union",
                    "marital_status_married":"Marital status: married",
                    "marital_status_separated_free_union":"Marital status: separated free union",
                    "marital_status_separated_marriage":"Marital status: separated marriage",
                    "marital_status_single":"Marital status: single",
                    "marital_status_widowed":"Marital status: widowed",
                    "grade_achieved_bachellors":"Grade achieved: bachellors",
                    "grade_achieved_doctorate":"Grade achieved: doctorate",
                    "grade_achieved_masters":"Grade achieved: masters",
                    "grade_achieved_none":"Grade achieved: none",
                    "grade_achieved_normal_basica":"Grade achieved: normal basica",
                    "grade_achieved_normal_licenciatura":"Grade achieved: licenciatura",
                    "grade_achieved_pre-school":"Grade achieved: pre-school",
                    "grade_achieved_preparatoria":"Grade achieved: preparatoria",
                    "grade_achieved_primaria":"Grade achieved: primaria",
                    "grade_achieved_secundaria":"Grade achieved: secundaria",
                    "grade_achieved_tec_com_studies_preparatoria":"Grade achieved: preparatoria with technical studies",
                    "grade_achieved_tec_com_studies_primaria":"Grade achieved: primaria with technical studies",
                    "grade_achieved_tec_com_studies_secundaria":"Grade achieved: secundaria with technical studies",
                    "region_Centre":"Region: Centre",
                    "region_Mexico City":"Region: Mexico City",
                    "region_North":"Region: North",
                    "region_South":"Region: South",
                    "strata_1st_strata":"Sociodemographic strata: 1st strata",
                    "strata_2nd_strata":"Sociodemographic strata: 2nd strata",
                    "strata_3rd_strata":"Sociodemographic strata: 3rd strata",
                    "strata_4th_strata":"Sociodemographic strata: 4th strata",
                    "age_health_info_adult_20-29":"Age: 20-29 years",
                    "age_health_info_adult_30-39":"Age: 30-39 years",
                    "age_health_info_adult_40-49":"Age: 40-49 years",
                    "age_health_info_adult_50-59":"Age: 50-59 years",
                    "age_health_info_adult_60-69":"Age: 60-69 years",
                    "age_health_info_adult_70-79":"Age: 70-79 years",
                    "age_health_info_adult_80-89":"Age: 80-89 years",
                    "sex_random_adult_female":"Sex: female",
                    "sex_random_adult_male":"Sex: male",
                    "glucose_value":"Blood glucose",
                    "hba1c_value":"Glucosilated hemoglobin",
                    "albumin_value":"Albumin",
                    "hdl_chol_value":"HDL Cholesterol",
                    "ldl_chol_value":"LDL Cholesterol",
                    "creatinine_value":"Creatinine",
                    "insulin_value":"Insulin",
                    "trig_value":"Triglycerides",
                    "days_intense_phy_act":"Days per week of intense physical activity",
                    "days_moderate_phy_act":"Days per week of moderate physical activity",
                    "days_walking":"Days waliking",
                    "hemoglobin_value":"Hemoglobin",
                    "minutes_sitting":"Minutes sitting down during the day",
                    "BMI_random_adult":"Body Mass Index",
                    "av_waist":"Waist circumference",
                    "av_systolic_bp":"Systolic Blood Pressure",
                    "av_dyastolic_bp":"Diastolic Blood Pressure",
                    "nut_cont_knowledge":"Knows packaging contains Nutritional Information",
                       "nut_inf_decision":"Uses Nutritional Information to make buying decision",
                       "use_dng":"Uses Nutritional Information: Daily Nutritional Guide",
                       "use_nut_seal":"Uses packaging info: Nutritional Seals",
                       "use_legends":"Uses packaging info: explicit nutritional legends",
                       "use_nut_inf":"Uses packaging info: Nutritional Information",
                       "use_ing_list":"Uses packaging info: ingredient list",
                       "use_none":"Uses packaging info: none",
                       "use_not_know":"Uses packaging info: does not know",
                       "unhealthy_product":"Identifies unhealthy product",
                       "sodium_level":"Identifies correct sodium level",
                       "calories":"Identifies correct number of calories",
                       "region_1":"Region: North",
                       "region_2":"Region: Centre",
                       "region_3":"Region: Mexico City",
                       "region_4":"Region: South",
                       "strata_1st_strata":"Sociodemographic strata: 1st strata",
                       "strata_2nd_strata":"Sociodemographic strata: 2nd strata",
                       "strata_3rd_strata":"Sociodemographic strata: 3rd strata",
                       "strata_4th_strata":"Sociodemographic strata: 4th strata",
                       "age_nut_know_adult_20-29":"Age: 20-29 years",
                       "age_nut_know_adult_30-39":"Age: 30-39 years",
                       "age_nut_know_adult_40-49":"Age: 40-49 years",
                       "age_nut_know_adult_50-59":"Age: 50-59 years",
                       "age_nut_know_adult_60-69":"Age: 60-69 years",
                       "age_nut_know_adult_70-79":"Age: 70-79 years",
                       "age_nut_know_adult_80-89":"Age: 80-89 years",
                       "sex_nut_know_adult_female":"Sex: female",
                       "sex_nut_know_adult_male":"Sex: male",
                       "buy_choice_almost always":"Buy choice based on packaging info: almost always",
                       "buy_choice_almost never":"Buy choice based on packaging info: almost never",
                       "buy_choice_always":"Buy choice based on packaging info: always",
                       "buy_choice_never":"Buy choice based on packaging info: never",
                       "buy_choice_sometimes":"Buy choice based on packaging info: sometimes",
                       "time_choice_Does not see it":"Time looking at packaging info: does not see it",
                       "time_choice_From 30 to 60 seconds":"Time looking at packaging info: 30 to 60 seconds",
                       "time_choice_Less than 30 seconds":"Time looking at packaging info: < 30 seconds",
                       "time_choice_More than a minute":"Time looking at packaging info: > 1 minute",
                       "energy_importance_Important":"Importance of Energy content info: important",
                       "energy_importance_Least important":"Importance of Energy content info: least important",
                       "energy_importance_Most important":"Importance of Energy content info: most important",
                       "energy_importance_Neutral":"Importance of Energy content info: neutral",
                       "energy_importance_Unimportant":"Importance of Energy content info: unimportant",
                       "sodium_importance_Important":"Importance of Sodium content info: important",
                       "sodium_importance_Least important":"Importance of Sodium content info: least important",
                       "sodium_importance_Most important":"Importance of Sodium content info: most important",
                       "sodium_importance_Neutral":"Importance of Sodium content info: neutral",
                       "sodium_importance_Unimportant":"Importance of Sodium content info: unimportant",
                       "sugars_importance_Important":"Importance of Sugars content info: important",
                       "sugars_importance_Least important":"Importance of Sugars content info: least important",
                       "sugars_importance_Most important":"Importance of Sugars content info: most important",
                       "sugars_importance_Neutral":"Importance of Sugars content info: neutral",
                       "sugars_importance_Unimportant":"Importance of Sugars content info: unimportant",
                       "fats_importance_Important":"Importance of Fats content info: important",
                       "fats_importance_Least important":"Importance of Fats content info: least important",
                       "fats_importance_Most important":"Importance of Fats content info: most important",
                       "fats_importance_Neutral":"Importance of Fats content info: neutral",
                       "fats_importance_Unimportant":"Importance of Fats content info: unimportant",
                       "sat_fats_importance_Important":"Importance of Saturated Fats content info: important",
                       "sat_fats_importance_Least important":"Importance of Saturated Fats content info: least important",
                       "sat_fats_importance_Most important":"Importance of Saturated Fats content info: most important",
                       "sat_fats_importance_Neutral":"Importance of Saturated Fats content info: neutral",
                       "sat_fats_importance_Unimportant":"Importance of Saturated Fats content info: unimportant",
                       "kinship_nut_know_adult_Grandparent":"Kinship: grandparent",
                       "kinship_nut_know_adult_Great grandparent":"Kinship: great-grandparent",
                       "kinship_nut_know_adult_Mother/father or uncle/aunt":"Kinship: father or Uncle/Aunt",
                       "kinship_nut_know_adult_Mother/father-in-law":"Kinship: mother/father-in-law",
                       "kinship_nut_know_adult_No kinship":"Kinship: no kinship",
                       "kinship_nut_know_adult_Parent":"Kinship: parent",
                       "kinship_nut_know_adult_Parent or uncle/aunt":"Kinship: parent or uncle/aunt",
                       "kinship_nut_know_adult_Partner":"Kinship: partner",
                       "kinship_nut_know_adult_Partner or brother/sister-in-law":"Kinship: partner or brother/sister-in-law",
                       "kinship_nut_know_adult_Sibling":"Kinship: sibling",
                       "kinship_nut_know_adult_Sibling or brother/sister-in-law":"Kinship: sibling or brother/sister-in-law",
                       "kinship_nut_know_adult_Sibling or cousin":"Kinship: sibling or cousin",
                       "kinship_nut_know_adult_Unknown":"Kinship: unknown"}

feat_order_summary_unimodal = ["hired_aid","has_TV","has_paid_TV","has_radio","has_audio_system","has_computer","has_cell_phone",
                        "has_internet","has_phone","has_iron","has_blender","has_refrigerator","has_gas_stove","has_other_stove",
                        "has_wash_dry","has_microwave","cooking_room_kitchen","cook_sleep","food_expense",
                        "result_elcsa_Food safety","result_elcsa_Mild insecurity","result_elcsa_Moderate insecurity",
                        "result_elcsa_Severe insecurity","exp_fruits", "exp_vegetables", "exp_corn", "exp_bread", "exp_grains", "exp_oil_sugar",
                         "exp_meat", "exp_dairy", "exp_eggs", "exp_snacks", "exp_fast_food", "exp_bottled_water", 
                         "exp_soda", "exp_alcohol", "exp_tobacco", "exp_not_homemade", "total_food_expense", 
                         "total_health_expense", "ob_diag", "dm_diag","hbp_diag","cvd_ha_hi","cvd_chest_angina", 
                        "cvd_heart_failure","kd_diag_uti","kd_diag_k_stones", 
                        "kd_diag_renal_fail","chol_diag","trig_diag","fmh_father_dm",
                        "fmh_father_hbp","fmh_father_hi","fmh_father_chol_tri","fmh_mother_dm",
                        "fmh_mother_hbp","fmh_mother_hi","fmh_mother_chol_tri","fmh_sibling_dm",
                        "fmh_sibling_hbp","fmh_sibling_hi","fmh_sibling_chol_tri","violence",
                        "present_smoker","past_smoker","sight_aid","hearing_aid","walk_difficulty",
                        "memory_difficulty","self_care_difficulty","communication_difficulty",
                        "sex_random_adult","hc_inst_IMSS","hc_inst_ISSSTE","hc_inst_ISSSTE_st",
                        "hc_inst_PEMEX","hc_inst_Defensa","hc_inst_Marina","hc_inst_SSA","hc_inst_IMSS_Pro",
                        "hc_inst_pharma","hc_inst_private","hc_inst_selfmed","hc_inst_other",
                        "hc_inst_doesnotgo","hc_inst_doesnotknow","speak_ind_lang","attend_school",
                        "grade_achieved","marital_status","worked_hours","diff_use_legs","diff_see",
                        "diff_use_arms","diff_learn","diff_hear","diff_self_care","diff_speak",
                        "diff_daily_act","fruit_intake","vegetable_intake","legumes_intake",
                        "meat_intake","proc_meat_intake","fast_food_intake","sweets_intake",
                        "sug_cereal_intake","nd_sug_bev_intake","water_intake","dairy_sug_bev_intake",
                        "dairy_intake","egg_intake","kinship_health_info_adult_Grandparent",
                        "kinship_health_info_adult_Great grandparent","kinship_health_info_adult_Mother/father or uncle/aunt",
                        "kinship_health_info_adult_Mother/father-in-law","kinship_health_info_adult_No kinship",
                        "kinship_health_info_adult_Parent","kinship_health_info_adult_Parent or uncle/aunt",
                        "kinship_health_info_adult_Partner","kinship_health_info_adult_Partner or brother/sister-in-law",
                        "kinship_health_info_adult_Sibling","kinship_health_info_adult_Sibling or cousin",
                        "kinship_health_info_adult_Unknown","marital_status_divorced","marital_status_free_union",
                        "marital_status_married","marital_status_separated_free_union","marital_status_separated_marriage",
                        "marital_status_single","marital_status_widowed","grade_achieved_bachellors","grade_achieved_doctorate",
                        "grade_achieved_master","grade_achieved_none","grade_achieved_normal_basica","grade_achieved_normal_licenciatura",
                        "grade_achieved_pre-school","grade_achieved_preparatoria","grade_achieved_primaria","grade_achieved_secundaria",
                        "grade_achieved_tec_com_studies_preparatoria","grade_achieved_tec_com_studies_primaria",
                        "grade_achieved_tec_com_studies_secundaria","region_Centre","region_Mexico City","region_North","region_South",
                        "strata_1st_strata","strata_2nd_strata","strata_3rd_strata","strata_4th_strata","age_health_info_adult_20-29",
                        "age_health_info_adult_30-39","age_health_info_adult_40-49","age_health_info_adult_50-59","age_health_info_adult_60-69",
                        "age_health_info_adult_70-79","age_health_info_adult_80-89","sex_random_adult_female","sex_random_adult_male",
                        "glucose_value","hba1c_value","albumin_value","hdl_chol_value","ldl_chol_value",
                         "creatinine_value","insulin_value","trig_value","days_intense_phy_act",
                         "days_moderate_phy_act","days_walking","hemoglobin_value","minutes_sitting",
                         "BMI_random_adult","av_waist","av_systolic_bp","av_dyastolic_bp",
                         "nut_cont_knowledge","nut_inf_decision","use_dng","use_nut_seal","use_legends",
                        "use_nut_inf","use_ing_list","use_none","use_not_know","unhealthy_product",
                        "sodium_level","calories","region_1","region_2","region_3","region_4","strata_1st_strata",
                        "strata_2nd_strata","strata_3rd_strata","strata_4th_strata","age_nut_know_adult_20-29",
                        "age_nut_know_adult_30-39","age_nut_know_adult_40-49","age_nut_know_adult_50-59",
                        "age_nut_know_adult_60-69","age_nut_know_adult_70-79","age_nut_know_adult_80-89",
                        "sex_nut_know_adult_female","sex_nut_know_adult_male","buy_choice_almost always",
                        "buy_choice_almost never","buy_choice_always","buy_choice_never","buy_choice_sometimes",
                        "time_choice_Does not see it","time_choice_From 30 to 60 seconds","time_choice_Less than 30 seconds",
                        "time_choice_More than a minute","energy_importance_Important","energy_importance_Least important",
                        "energy_importance_Most important","energy_importance_Neutral","energy_importance_Unimportant",
                        "sodium_importance_Important","sodium_importance_Least important","sodium_importance_Most important",
                        "sodium_importance_Neutral","sodium_importance_Unimportant","sugars_importance_Important",
                        "sugars_importance_Least important","sugars_importance_Most important","sugars_importance_Neutral",
                        "sugars_importance_Unimportant","fats_importance_Important","fats_importance_Least important",
                        "fats_importance_Most important","fats_importance_Neutral","fats_importance_Unimportant","sat_fats_importance_Important",
                        "sat_fats_importance_Least important"]